/* Automatically generated by configure - do not modify! */
#define VERSION "1.1a"
#define PACKAGE "bunnyushare"
#define PACKAGE_NAME "Bunny_uShare"
#define SYSCONFDIR "/usr/local/etc"
#define LOCALEDIR "/usr/local/share/locale"
#define CONFIG_NLS 1
